version: "3.8"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SQLITE_DB_PATH=/app/database.sqlite
    volumes:
      - sqlite-data:/app
volumes:
  sqlite-data: {}
